# Generated by Django 6.0.6 on 2026-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_transactionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
        ),
    ]
