# Generated by Django 6.0.6 on 2026-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bankaccount_daily_limit_bankaccount_monthly_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
