# Generated by Django 6.0.6 on 2026-06-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_transactionrecord_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
    ]
