# Generated by Django 6.0.6 on 2026-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_remove_bankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
